[s3]
bucket = "my-backup-bucket"

[reporting]
htmlPath = "./reports"
errorRecipients = ["ops@example.com"]

[[jobs]]
name = "Daily Redis Backup"
path = "/var/lib/redis/dump.rdb"
s3KeyPrefix = "redis-backups/"

[jobs.policy]
retentionCount = 7
frequency = "daily"
